server:
  port: 8084

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/canteen_auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: tintin113
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT secret lives in config — not hardcoded in Java
# This exact value must be in application.yml of every service
jwt:
  secret: canteen-ordering-app-secret-key-2024!!

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true