server:
  port: 8081

spring:
  application:
    name: menu-service

  datasource:
    url: jdbc:mysql://localhost:3306/canteen_menu_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: tintin113
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Same value as all other services
jwt:
  secret: canteen-ordering-app-secret-key-2024!!

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
internal:
  secret: canteen-internal-service-secret-2024
